name: Sync Dev with Main

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✨ THIS IS REQUIRED for pushing to branches

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync dev with main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream main
          git checkout dev
          git reset --hard upstream/main
          git push origin dev --force
