name: Smart Sync Dev with Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Check if dev is behind main
        id: check_diff
        run: |
          git fetch origin dev
          if git rev-list origin/dev..origin/main | grep .; then
            echo "needs_sync=true" >> $GITHUB_OUTPUT
          else
            echo "Dev is up-to-date with main"
            echo "needs_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR from main to dev
        if: steps.check_diff.outputs.needs_sync == 'true'
        run: |
          gh pr create \
            --base dev \
            --head main \
            --title "Sync: main → dev" \
            --body "Auto-generated PR to keep dev in sync with main after push."

      # Optional: Auto-merge if checks pass
      - name: Enable auto-merge
        if: steps.check_diff.outputs.needs_sync == 'true'
        run: |
          PR_ID=$(gh pr list --head main --base dev --json number -q '.[0].number')
          gh pr merge $PR_ID --auto --squash
