name: Sync Dev with Main

on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  

jobs:
  sync-dev:
    name: Sync dev branch with main
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Sync dev with main
        run: |
          # Fetch all branches
          git fetch origin
          
          # Check if dev branch exists
          if git ls-remote --heads origin dev | grep dev; then
            echo "Dev branch exists, syncing with main..."
            
            # Checkout dev branch
            git checkout dev
            
            # Merge main into dev
            git merge --no-ff origin/main -m "Merge main into dev to keep branches in sync"
            
            # Push changes to dev
            git push origin dev
            
            echo "Successfully synced dev branch with main"
          else
            echo "Dev branch doesn't exist, creating from main..."
            
            # Create dev branch from main
            git checkout -b dev
            
            # Push new dev branch
            git push origin dev
            
            echo "Successfully created dev branch from main"
          fi